(******************************************************************************)
(*                                                                            *)
(*                        Market Temporal Semantics                           *)
(*                                                                            *)
(*     Instants, time zones, DST transitions, holidays, early closes,         *)
(*     trading sessions, and bar/window bucketing. Totality across DST        *)
(*     gaps, overlaps, and exact session boundaries. All session and          *)
(*     bucketing functions extract without option types or exceptions.        *)
(*     Serves as a drop-in kernel for any system that maps raw UTC            *)
(*     timestamps to market-local session time and OHLC/VWAP bars.            *)
(*                                                                            *)
(*     "Time is the most valuable thing a man can spend."                     *)
(*     – Theophrastus, c. 300 BC                                              *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: February 10, 2026                                                *)
(*     License: Proprietary — All Rights Reserved                             *)
(*                                                                            *)
(******************************************************************************)
